// Central preset registry — the desktop equivalent of the PowerShell presets/ and
// tiers/ in the repo root. One list, ordered smallest to largest, used by both the
// model picker UI and the server launcher. Sizes/quants verified against live
// Hugging Face model cards; tok/s and VRAM figures are estimates, not measurements —
// see the main README's "what I verified vs what you need to verify" section.

const PRESETS = [
  {
    id: "cpu-tiny",
    label: "CPU-only",
    model: "Qwen2.5-Coder-3B-Instruct",
    tagline: "No GPU needed. The floor of this app — works on any laptop.",
    group: "cpu",
    requirement: "Any CPU, 8GB+ RAM",
    hfRepo: "bartowski/Qwen2.5-Coder-3B-Instruct-GGUF",
    hfPattern: /Q4_K_M/i,
    approxSizeGB: 1.9,
    ngl: 0,
    cpuMoe: null,
    ctxDefault: 8192,
    cacheQuant: false,
    notes: "Slowest and weakest tool-calling of any preset here — there's nothing smaller to fall back to.",
  },
  {
    id: "gpu-tiny",
    label: "4-6GB VRAM",
    model: "Qwen2.5-Coder-3B-Instruct",
    tagline: "Older or entry GPUs. Fully GPU-resident.",
    group: "gpu",
    requirement: "4-6GB VRAM, 8GB+ RAM",
    hfRepo: "bartowski/Qwen2.5-Coder-3B-Instruct-GGUF",
    hfPattern: /Q4_K_M/i,
    approxSizeGB: 1.9,
    ngl: 99,
    cpuMoe: null,
    ctxDefault: 16384,
    cacheQuant: false,
    notes: "Fast, but weak agentic tool-calling at this size — expect to double-check edits.",
  },
  {
    id: "gpu-small",
    label: "6-8GB VRAM",
    model: "Qwen2.5-Coder-7B-Instruct",
    tagline: "Common mid-range cards. Fully GPU-resident.",
    group: "gpu",
    requirement: "6-8GB VRAM, 16GB+ RAM",
    hfRepo: "bartowski/Qwen2.5-Coder-7B-Instruct-GGUF",
    hfPattern: /Q4_K_M/i,
    approxSizeGB: 4.4,
    ngl: 99,
    cpuMoe: null,
    ctxDefault: 32768,
    cacheQuant: false,
    notes: "Noticeably more reliable than the 3B tier for multi-step tasks.",
  },
  {
    id: "gpu-medium",
    label: "10-12GB VRAM",
    model: "Qwen2.5-Coder-14B-Instruct",
    tagline: "Fills the gap between 7B and the big 30B MoE. Fully GPU-resident.",
    group: "gpu",
    requirement: "10-12GB VRAM, 16GB+ RAM",
    hfRepo: "bartowski/Qwen2.5-Coder-14B-Instruct-GGUF",
    hfPattern: /Q4_K_M/i,
    approxSizeGB: 9.0,
    ngl: 99,
    cpuMoe: null,
    ctxDefault: 32768,
    cacheQuant: true,
    notes: "Best quality-per-GB dense model in this app; still below the MoE tiers on tool-calling.",
  },
  {
    id: "gpu-fast",
    label: "16GB+ VRAM",
    model: "Qwen3-Coder-30B-A3B-Instruct",
    tagline: "MoE with only ~3B active params per token — fast and far more reliable at tool-use.",
    group: "gpu",
    requirement: "16GB+ VRAM (set CPU offload below if VRAM is tight), 32GB+ RAM",
    hfRepo: "unsloth/Qwen3-Coder-30B-A3B-Instruct-GGUF",
    hfPattern: /UD-Q4_K_XL/i,
    approxSizeGB: 19,
    ngl: 99,
    cpuMoe: 0,
    cpuMoeAdjustable: true,
    ctxDefault: 65536,
    cacheQuant: true,
    notes: "On a 16GB card this is tight — raise the CPU-offload slider (try 6) if you hit out-of-memory.",
  },
  {
    id: "crucible",
    label: "Balanced (default for big rigs)",
    model: "Qwen3-Coder-Next (Q4_K_XL)",
    tagline: "80B total / 3B active MoE split across GPU + system RAM. Fast and reliable.",
    group: "big",
    requirement: "~24-32GB VRAM + 32GB+ RAM (e.g. RTX 5090)",
    hfRepo: "unsloth/Qwen3-Coder-Next-GGUF",
    hfPattern: /UD-Q4_K_XL/i,
    approxSizeGB: 46,
    ngl: 99,
    cpuMoe: 16,
    cpuMoeAdjustable: true,
    ctxDefault: 65536,
    cacheQuant: true,
    notes: "Requires DDR5 EXPO/XMP enabled in BIOS for full speed — generation is RAM-bandwidth-bound.",
  },
  {
    id: "max",
    label: "Max quality",
    model: "Qwen3-Coder-Next (Q6_K_XL)",
    tagline: "Same model as Balanced, near-lossless quant. The most capable reliable agent this app ships.",
    group: "big",
    requirement: "~30-32GB VRAM + 48GB+ RAM",
    hfRepo: "unsloth/Qwen3-Coder-Next-GGUF",
    hfPattern: /UD-Q6_K_XL/i,
    approxSizeGB: 73,
    ngl: 99,
    cpuMoe: 26,
    cpuMoeAdjustable: true,
    ctxDefault: 131072,
    cacheQuant: true,
    notes: "~10-25% slower than Balanced for near-full-precision quality.",
  },
  {
    id: "reasoning",
    label: "Reasoning (secondary)",
    model: "gpt-oss-120b (native MXFP4)",
    tagline: "Strongest raw one-shot coder/reasoner that fits — but flakier at tool-calling. Not a daily driver.",
    group: "big",
    requirement: "~30-32GB VRAM + 48GB+ RAM",
    hfRepo: "ggml-org/gpt-oss-120b-GGUF",
    hfPattern: /mxfp4/i,
    approxSizeGB: 60,
    ngl: 99,
    cpuMoe: 20,
    cpuMoeAdjustable: true,
    ctxDefault: 131072,
    cacheQuant: false,
    reasoningEffort: "high",
    notes: "Tool-calling depends on OpenAI's Harmony format and is known-flaky in agent harnesses — keep it as a secondary.",
  },
];

function getPreset(id) {
  const p = PRESETS.find((x) => x.id === id);
  if (!p) throw new Error(`Unknown preset: ${id}`);
  return p;
}

module.exports = { PRESETS, getPreset };
